page_title: "Build Stateful Agentic AI graph"

llm_config:
  providers:
    Groq:
      models:
        - "openai/gpt-oss-120b"
        - "llama3-8b-8192"
        - "llama3-70b-8192"
        - "gemma2-9b-it"
        
    Rakuten:
      api_url: "https://api.ai.public.rakuten-it.com/openai/v1"
      models:
        - "gpt-5"        
    OpenAI:
      models:
        - "gpt-5"
        - "gpt-4o"
        - "gpt-4-turbo"
        - "gpt-4o-mini"
    Anthropic:
      models:
        - "claude-3-sonnet"
        - "claude-3-opus"

usecases:
  options: 
    - "Basic Chatbot"
    - "Chatbot With Web Search"
    - "AI News"
